### ISSUE TITLE
Reload images for only current tab

### ISSUE THREAD

**Issue by grill02** [tiborbarsi/image-video-block-browser-addon#10]
Hello,
I use this addon to save net traffic, so I would only like to reload images for current tab on change. I understand it will take time to add this feature. In the meanwhile, thereis one line in the js file that needs to change. Can you please mention the correct code.

**Comment by tiborbarsi** [comment]
I'm working on this feature.
In the meanwhile, removing this will stop downloading (blocked) images on unblock. [link](https://github.com/tiborbarsi/image-video-block-browser-addon/blob/master/src/content_scripts/content_script.js#L24)

**Comment by tiborbarsi** [comment]
Implemented.

**Comment by grill02** [comment]
Thanks!
